# Generated by Django 5.2.4 on 2025-08-17 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientfinance_monthlypayment_collectionrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_controls', to='clients.client')),
            ],
            options={
                'verbose_name': 'operational control',
                'verbose_name_plural': 'operational controls',
                'ordering': ['-year', 'client__name'],
                'unique_together': {('client', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre'), (13, 'Declaración Jurada Anual')])),
                ('presentation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_declarations', to='clients.operationalcontrol')),
            ],
            options={
                'verbose_name': 'monthly declaration',
                'verbose_name_plural': 'monthly declarations',
                'ordering': ['month'],
                'unique_together': {('operational_control', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalPDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_type', models.CharField(choices=[('PDT_601', 'PDT 601'), ('PDT_616', 'PDT 616'), ('PDT_617', 'PDT 617'), ('PDT_621', 'PDT 621'), ('PDT_709', 'PDT 709'), ('PDT_710', 'PDT 710'), ('OTHER', 'Otro')], max_length=10)),
                ('pdt_name', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('presentation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('presented', 'Presentada'), ('observed', 'Observada'), ('accepted', 'Aceptada')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='additional_pdts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operational_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_pdts', to='clients.operationalcontrol')),
            ],
            options={
                'verbose_name': 'additional PDT',
                'verbose_name_plural': 'additional PDTs',
                'ordering': ['-presentation_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_type', models.CharField(choices=[('PDT_601', 'PDT 601'), ('PDT_616', 'PDT 616'), ('PDT_617', 'PDT 617'), ('PDT_621', 'PDT 621'), ('PDT_709', 'PDT 709'), ('PDT_710', 'PDT 710')], max_length=10)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('presented', 'Presentada'), ('observed', 'Observada'), ('accepted', 'Aceptada')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tax_declarations/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('monthly_declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='clients.monthlydeclaration')),
            ],
            options={
                'verbose_name': 'tax declaration',
                'verbose_name_plural': 'tax declarations',
                'ordering': ['pdt_type'],
            },
        ),
        migrations.DeleteModel(
            name='CollectionRecord',
        ),
    ]
