# Generated by Django 5.2.4 on 2025-08-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_operationalcontrol_monthlydeclaration_additionalpdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfinance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='clients.client'),
        ),
    ]
